### ISSUE TITLE
import should be require in src/tasks/init.js. cannot execute sandbox.run() from node script

### ISSUE THREAD

**Issue by stewartschillingsdi** [adobe/reactor-sandbox#62]
### Expected Behaviour
Per the docs, I should be able to use this package within a node script.  See https://github.com/adobe/reactor-sandbox#advanced-integration-with-node-scripts

This issue was introduced with the most recent release, tagged 11.1.6

### Actual Behaviour
When attempting to run the sandbox from with my node script, I get the following error: 
> ./scripts/sandbox-service.js build --watch --mode development

/Users/stewartschilling/Desktop/repos/aa-beacon-tailor-launch-extension/node_modules/@adobe/reactor-sandbox/src/tasks/init.js:22
import { PLATFORMS } from '../helpers/sharedConstants';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1116:16)
    at Module._compile (internal/modules/cjs/loader.js:1164:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/Users/stewartschilling/Desktop/repos/aa-beacon-tailor-launch-extension/node_modules/@adobe/reactor-sandbox/src/lib.js:13:14)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
#### Steps to Reproduce
Create and attempt to run a node script as follows: 
#!/usr/bin/env node
const sandbox = require('@adobe/reactor-sandbox');
sandbox.run();

#### Sample Code that illustrates the problem
See Above.

**Comment by thebenrob** [comment]
@adobe export issue Jira project pdcl as Bug

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL as bug

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL as Bug
